{% set name = "pystemmer" %}
{% set version = "2.2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 959be98ef3a72f37697288864e93789dc817fffda959499e426964b11e618a3e

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  script_env:
    - PYSTEMMER_SYSTEM_LIBSTEMMER=false

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - cython >=0.28.5,<1.0
    - setuptools >=18.0
    - pip
  run:
    - python

test:
  imports:
    - Stemmer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/snowballstem/pystemmer/
  summary: Snowball stemming algorithms, for information retrieval
  license: MIT AND BSD-3-Clause
  license_file:
    - LICENSE
    - libstemmer_c-2.2.0/COPYING

extra:
  recipe-maintainers:
    - thewchan
