{% set version = "2.2.0.3" %}

package:
  name: pystemmer
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pystemmer/pystemmer-{{ version }}.tar.gz
  sha256: 9ac74c8d0f3358dbb050f64cddbb8d55021d831d92305d7c20780ea8d6c0020e

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - cython >=0.28.5
    - pip
    - python
    - setuptools >=18.0
  run:
    - python

test:
  imports:
    - Stemmer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/snowballstem/pystemmer/
  summary: Snowball stemming algorithms, for information retrieval
  license: MIT AND BSD-3-Clause
  license_file:
    - LICENSE
    - libstemmer_c-2.2.0/COPYING

extra:
  recipe-maintainers:
    - thewchan
